language: perl
perl:
  - "5.20"
  - "5.16"
  - "5.12"
  - "5.10"
env:
  - "HARNESS_OPTIONS=j9"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install redis-server
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage IO::Socket::SSL"
  - "cpanm -n --installdeps ."
notifications:
  email: false
